Repository faulty337/agitClone-BE, pull requests merged in 2022-12, with the labels that each got.

#5 feat: 게시글 생성 기능 구현
  agitClone/src/main/java/com/hanghae99/agitclone/post/controller/PostController.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/dto/RequestPostDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/dto/ResponsePostDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/entity/Post.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/mapper/PostMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/repository/PostRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/service/PostService.java
Labels: feature

#3 feat: Comment 작성 기능 구현, dto, service, repository 등 기본작업 구현완료
  agitClone/src/main/java/com/hanghae99/agitclone/comment/controller/CommentController.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/dto/CommentRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/dto/CommentResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/entity/Comment.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/mapper/CommentMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/repository/CommentRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/service/CommentService.java
Labels: good first issue, feature

#15 feat: 회원가입 및 로그인, 씨큐리티 API
  agitClone/build.gradle
  agitClone/src/main/java/com/hanghae99/agitclone/common/ResponseMessage.java
  agitClone/src/main/java/com/hanghae99/agitclone/common/exception/ErrorCode.java
  agitClone/src/main/java/com/hanghae99/agitclone/security/UserDetailsImpl.java
  agitClone/src/main/java/com/hanghae99/agitclone/security/UserDetailsServiceImpl.java
  agitClone/src/main/java/com/hanghae99/agitclone/security/config/WebSecurityConfig.java
  agitClone/src/main/java/com/hanghae99/agitclone/security/jwt/JwtAuthFilter.java
  agitClone/src/main/java/com/hanghae99/agitclone/security/jwt/JwtUtil.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/controller/UserController.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/dto/IdcheckRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/dto/LoginRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/dto/SignupRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/dto/UserinfoResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/entity/Users.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/mapper/UserMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/repository/UserRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/service/UserService.java
  agitClone/src/main/resources/application-dbSetting.properties
Labels: feature

#14 feat: 댓글 수정,삭제 API완료, 등록 refactor
  agitClone/src/main/java/com/hanghae99/agitclone/comment/controller/CommentController.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/dto/CommentResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/service/CommentService.java
Labels: feature

#21 feat: 댓글 API 예외처리
  agitClone/src/main/java/com/hanghae99/agitclone/comment/controller/CommentController.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/entity/Comment.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/mapper/CommentMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/service/CommentService.java
Labels: feature

#25 feat: 아지트 멤버 초대 API 구현 완료.Feature/#19
  agitClone/src/main/java/com/hanghae99/agitclone/agit/controller/AgitController.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/dto/AgitInviteRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/entity/AgitMember.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/mapper/AgitMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/repository/AgitMemberRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/service/AgitService.java
  agitClone/src/main/java/com/hanghae99/agitclone/common/exception/ErrorCode.java
Labels: feature, refactor

#28 feat: 아지트 리스트 API 구현 완료
  agitClone/src/main/java/com/hanghae99/agitclone/agit/controller/AgitController.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/dto/AgitRequestDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/dto/AgitResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/entity/Agit.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/entity/AgitMember.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/mapper/AgitMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/repository/AgitMemberRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/repository/AgitRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/service/AgitService.java
Labels: feature, refactor

#26 refactor: 댓글 API 예외처리 수정
  agitClone/src/main/java/com/hanghae99/agitclone/comment/controller/CommentController.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/dto/CommentResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/entity/Comment.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/mapper/CommentMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/comment/service/CommentService.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/entity/Post.java
Labels: refactor

#32 refactor: 회원가입 정규식 조건 추가
  agitClone/src/main/java/com/hanghae99/agitclone/common/exception/GlobalExceptionHandler.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/dto/SignupRequestDto.java
Labels: refactor

#30 feat: 아지트 참여 멤버 반환 API 구현 완료
  agitClone/src/main/java/com/hanghae99/agitclone/agit/controller/AgitController.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/dto/AgitListResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/dto/AgitMemberResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/mapper/AgitMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/repository/AgitMemberRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/agit/service/AgitService.java
  agitClone/src/main/java/com/hanghae99/agitclone/user/entity/Users.java
Labels: feature, refactor

#35 feat : 좋아요, 싫어요 API
  agitClone/src/main/java/com/hanghae99/agitclone/post/controller/PostLikeController.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/dto/PostHateDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/dto/PostLikeDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/dto/PostLikeResponseDto.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/entity/Post.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/entity/PostLike.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/mapper/PostLikeMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/mapper/PostMapper.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/repository/PostLikeRepository.java
  agitClone/src/main/java/com/hanghae99/agitclone/post/service/PostLikeService.java
Labels: feature
